## Create a sample lambda function to handle http requests and return a static HTML webpage 
import json

CONTENT = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Static HTML from Lambda</title>
</head>
<body>
    <h1>Hello from Business One!</h1>
    <p>This is a static HTML page generated by a Lambda function.</p>
</body>
</html>
"""

def handler(event, context):
    response = {
        'statusCode': 200,
        'headers': {
            'Content-Type': 'text/html'
        },
        'body': CONTENT
    }
    
    return response
